set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'vim-vdebug/vdebug'
Plugin 'zivyangll/git-blame.vim'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}
Plugin 'fatih/vim-go'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

colorscheme melon
set relativenumber
set history=30
set ruler
set nu
set shiftwidth=4
set autoindent
set nobackup
set ignorecase
set nowrap
set smartindent
set tabstop=4
set expandtab
set smarttab
set ts=4

set fencs=utf-8,gbk
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,gb2312,ucs-bom,cp936,big5,latin1
set termencoding=utf-8
set laststatus=2
set cmdheight=2
set ff=unix
set hlsearch
set cursorline
set statusline=%F%m%r%h%w
set tabpagemax=32
set tags=./tags;,tags;
set autochdir
set shell=/usr/bin/zsh
set switchbuf=newtab
set showmode


map <C-S> :!/bin/sh %<CR>
map <C-J> :!tail /tmp/errors.log<CR>
map <C-P> :!python %<CR>
map <C-L> :!/usr/bin/php -ln %<CR>
map <C-F> :!/usr/bin/php -f %<CR>
map <C-P> :!/usr/bin/python3 %<CR>
map <C-C> :!g++ % -o o && ./o<CR>
map <C-N> :!node %<CR>
map <C-G> :!go run %<CR>

let mapleader = ","
let g:mapleader = ","
nnoremap <Leader>s :<C-u>call gitblame#echo()<CR>
map <C-\> :tab vsplit<CR>:exec("tag ".expand("<cword>"))<CR>
