ZSH_THEME="melon"
DISABLE_AUTO_TITLE="true"
export ZSH=$HOME/.oh-my-zsh
export LC_CTYPE=en_US.UTF-8
plugins=(
    git
    zsh-autosuggestions 
)
. ~/.env
. $ZSH/oh-my-zsh.sh
. ~/dotrc/zsh/color
. ~/dotrc/zsh/funcs.zsh
. /root/dotrc/git/funcs.zsh
. ~/.alias/common
. ~/.alias/custom
