ZSH_THEME="fino"
DISABLE_AUTO_TITLE="true"
plugins=(
    git
    zsh-autosuggestions 
)
export ZSH=$HOME/.oh-my-zsh
. ~/.export/common
. ~/.export/custom
. ~/.env
source $ZSH/oh-my-zsh.sh
. ~/dotrc/zsh/color
. ~/dotrc/zsh/funcs.zsh
. /root/dotrc/git/funcs.zsh
. /root/.alias/common
. ~/.alias/custom
